### Numpy
- 데이터는 행열로 표현
- 행열 데이터 빠르게 계산을 해야합니다.
- 행렬 데이터 생성, 수정, 계산등을 빠르게 처리해주는 패키지
- 특징
    - C,C++,포트란으로 작성
    - 선형대수학을 빠르게 연산
        - 스칼라, 벡터, 메트릭스

In [3]:
import numpy as np

In [8]:
# 행렬 데이터 생성
# ndarray : 한가지 데이터 타임만 값으로 사용이 가능

In [5]:
array = np.array([1,2,3])
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [7]:
array2 = np.array(
    [[1,2,3],
    [4,5,6]],
)

array2, array2.ndim, array2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [10]:
# 행렬의 모양(shape) 변경하기
array2.reshape(3,2,1)

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [13]:
# 행렬 데이터의 선택 : offset index : masking

In [16]:
array2[1][:2]

array([4, 5])

In [17]:
array2[1,2] #array2[1][2]

6

In [18]:
#  데이터 수정

In [19]:
ls = [1,2,3]
ls[1] =5
ls

[1, 5, 3]

In [22]:
array2[1][2] = 10
array2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [24]:
#브로드 캐스팅
array2[0] = 0
array2

In [26]:
array2[0] = [7,8,9]
array2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

In [29]:
# 조건으로 선택
idx = array2 > 7
idx

array([[False,  True,  True],
       [False, False,  True]])

In [32]:
array2[idx] = 100
array2

array([[  7, 100, 100],
       [  4,   5, 100]])

In [33]:
# 행렬 데이터의 생성 2

In [34]:
data = np.zeros((2,3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
data.dtype

dtype('float64')

In [37]:
data2 = data.astype("int")
data2.dtype

dtype('int64')

In [39]:
data = np.ones((2,3,4))
data

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [42]:
# arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [43]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [45]:
np.arange(5,10,2)

array([5, 7, 9])

In [47]:
import pandas as pd
np.random.seed(0)
data = pd.Series(np.random.randint(1,10,size=5), index=list('ABCDE'))

In [48]:
data

A    6
B    1
C    4
D    4
E    8
dtype: int64

In [51]:
result = data + 2

In [52]:
result['B'] = 10

In [53]:
result = result +  3

In [54]:
result['B']

13