In [2]:
from sklearn.datasets import load_iris # 사이킷 런패키지 임포트

In [13]:
iris = load_iris() # 데이터로드
iris.data[1, :]

array([4.9, 3. , 1.4, 0.2])

In [10]:
x1 = np.array([[5.1], [3.5], [1.4], [0.2]])
x1

array([[5.1],
       [3.5],
       [1.4],
       [0.2]])

In [11]:
x1 = np.array([5.1, 3.5, 1.4, 0.2])
x1

array([5.1, 3.5, 1.4, 0.2])

In [15]:
x2 = np.array([4.9, 3., 1.4, 0.2])
x2

array([4.9, 3. , 1.4, 0.2])

In [20]:
from sklearn.datasets import load_digits # 패키지 임포트
import matplotlib.pylab as plt

digits = load_digits() # 데이터 로드
samples = [0, 10, 20, 30, 1, 11, 21, 31] # 선택된 이미지 번호
d = []
for i in range(8):
    d.append(digits.images[samples[i]])
    
plt.figure(figsize=(8,2))
for i in range(8):
    plt.subplot(1, 8, i+1)
    plt.imshow(d[i], interpolation='nearest', cmap=plt.cm.bone_r)
    plt.grid(False);
    plt.xticks([])
    plt.yticks([])
    plt.title('image {}'.format(i+1))
plt.suptitle('숫자 0과 1 이미지')
plt.tight_layout()
plt.show()

In [19]:
plt.figure(figsize=(10,2))
plt.show()