In [1]:
import numpy as np

A = (np.arange(9) -4).reshape((3,3))
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [2]:
np.linalg.norm(A)

7.745966692414834

In [3]:
np.trace(np.eye(3))

3.0

In [4]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(A)

-9.51619735392994e-16

In [6]:
x = np.array([[1,3,5],[2,3,7],[9,1,2],[4,8,7],[6,5,2]])
np.linalg.matrix_rank(x)

3

In [9]:
B = np.array([[5,-2],[1,-3]])
w1 , v1  = np.linalg.eig(B)

w1,v1

(array([ 4.74165739, -2.74165739]),
 array([[0.99176035, 0.25013046],
        [0.12810698, 0.96821214]]))