In [2]:
import numpy as np

A = np.array([[1,1,0], [0,1,1], [1,1,1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [3]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [13]:
b = np.array([[2],[2],[3]])
b

array([[2],
       [2],
       [3]])

In [14]:
x = Ainv @ b
x

array([[1.],
       [1.],
       [1.]])

In [15]:
A @ x - b

array([[0.],
       [0.],
       [0.]])

In [18]:
x, reisd, rank, s = np.linalg.lstsq(A, b)
x

<ipython-input-18-f8f7a7e6e2e9>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, reisd, rank, s = np.linalg.lstsq(A, b)


array([[1.],
       [1.],
       [1.]])

In [22]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0,4,5,6]]
b = y[:4]
Ainv = np.linalg.inv(A)
X = Ainv @ b
X

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

In [23]:
A = np.array([[1,1,0],[0,1,1],[1,1,1],[1,1,2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [31]:
b = np.array([[2],[2],[3],[4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [32]:
Apinv = np.linalg.inv(A.T @ A) @ A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [33]:
x = Apinv @ b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [35]:
A @ x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [36]:
x , resid, rank, s = np.linalg.lstsq(A, b)
x

<ipython-input-36-e28fb52c0dfa>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x , resid, rank, s = np.linalg.lstsq(A, b)


array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [37]:
resid,  np.linalg.norm(A @ x - b) ** 2

(array([0.00166667]), 0.0016666666666666698)

In [38]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [39]:
Xpinv = np.linalg.inv(X.T @ X) @ X.T
Xpinv

array([[ 1.09231858e-04,  8.96511045e-05,  1.43390247e-04, ...,
         9.92573160e-05,  9.76945713e-05,  9.00841038e-05],
       [-4.72690165e-05, -1.21875540e-04, -1.63389620e-04, ...,
         9.24841138e-05,  8.61893367e-05,  1.02954680e-04],
       [-1.04927299e-03,  9.41663987e-05,  2.53311215e-04, ...,
         1.16960096e-04,  1.09836326e-04,  9.11452898e-07],
       ...,
       [-5.61436625e-04, -2.96418946e-04, -4.00322073e-04, ...,
         1.85404958e-03,  1.85182324e-03,  2.21824093e-03],
       [ 3.37924487e-06,  1.47110306e-06, -4.60821286e-06, ...,
        -1.20096147e-05, -1.20573000e-05, -6.30925747e-06],
       [-3.79769286e-04, -1.98270828e-04, -3.32088952e-04, ...,
        -7.97353922e-04, -7.65739790e-04, -7.77591904e-04]])

In [ ]:
X