In [3]:
from numpy.linalg import svd
import numpy as np

A =  np.array([[3, -1], [1,3], [1,1]])
U, S, VT = svd(A)

In [4]:
U

array([[-4.08248290e-01,  8.94427191e-01, -1.82574186e-01],
       [-8.16496581e-01, -4.47213595e-01, -3.65148372e-01],
       [-4.08248290e-01, -1.94289029e-16,  9.12870929e-01]])

In [5]:
S

array([3.46410162, 3.16227766])

In [6]:
np.diag(S, 1)[:, 1:]

array([[3.46410162, 0.        ],
       [0.        , 3.16227766],
       [0.        , 0.        ]])

In [7]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

AttributeError: module 'numpy' has no attribute 'daig'