In [1]:
import numpy as np

x1 = np.array([1,2])
x2 = np.array([3,3])
x3 = np.array([10, 14])
2 * x1 + x2 - 0.5 * x3

array([0., 0.])

In [3]:
X1 = np.array([[1,3],[2,4]])
np.linalg.matrix_rank(X1)

2

In [6]:
X2 = np.array([[1,3,5],[2,3,7]])
np.linalg.matrix_rank(X2)

2

In [9]:
X3 = np.array([1,1])
X3_1 = X3.T @ X3
np.linalg.matrix_rank(X3_1)

1

In [15]:
X4 = np.array([[1,1],[1,-1]])
X4_1 = X4.T @ X4
np.linalg.matrix_rank(X4_1)

2

In [20]:
g1 = np.array([1,1]) / np.sqrt(2)
g2 = np.array([-1,1]) / np.sqrt(2)
x = np.array([2,2])

In [21]:
A = np.vstack([g1,g2]).T
A

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [22]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [23]:
Ainv.dot(x)

array([2.82842712, 0.        ])

In [24]:
g1 = np.array([1,0.75]) 
g2 = np.array([-1,0.75])
x1 = np.array([1,0])
x2 = np.array([1,2])
x3 = np.array([-1,2])

In [25]:
A = np.vstack([g1,g2]).T
A

array([[ 1.  , -1.  ],
       [ 0.75,  0.75]])

In [26]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0.5       ,  0.66666667],
       [-0.5       ,  0.66666667]])

In [27]:
Ainv.dot(x1) , Ainv.dot(x2), Ainv.dot(x3)

(array([ 0.5, -0.5]),
 array([1.83333333, 0.83333333]),
 array([0.83333333, 1.83333333]))

In [29]:
A = np.array([[1, -2], [2, -3]])
w1 , v1 = np.linalg.eig(A)

print(w1)
print(v1)

[-0.99999998 -1.00000002]
[[0.70710678 0.70710678]
 [0.70710678 0.70710678]]


In [30]:
B = np.array([[2,3],[2,1]])
w2, v2 = np.linalg.eig(B)

print(w2)
print(v2)


[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [31]:
v2

array([[ 0.83205029, -0.70710678],
       [ 0.5547002 ,  0.70710678]])

In [32]:
v2_inv = np.linalg.inv(v2)
v2_inv

array([[ 0.72111026,  0.72111026],
       [-0.56568542,  0.84852814]])

In [33]:
v2 @ np.diag(w2) @ v2_inv

array([[2., 3.],
       [2., 1.]])

In [36]:
A = np.array([[60.,30.,20.],
              [30.,20.,15,],
              [20.,15.,12.]])

w , V  = np.linalg.eig(A)
w1, w2, w3 = w
v1 = V[:, 0:1]
v2 = V[:, 1:2]
v3 = V[:, 2:3]
A1 = v1 @ v1.T
A2 = v2 @ v2.T
A3 = v3 @ v3.T

In [37]:
w

array([84.49913563,  7.33962395,  0.16124042])

In [38]:
w1 * A1

array([[57.79768857, 32.13739648, 22.59357583],
       [32.13739648, 17.8694387 , 12.56276371],
       [22.59357583, 12.56276371,  8.83200836]])

In [39]:
w2 * A2

array([[ 2.19968372, -2.12270483, -2.60775134],
       [-2.12270483,  2.04841985,  2.51649195],
       [-2.60775134,  2.51649195,  3.09152039]])

In [40]:
w3 * A3

array([[ 0.00262772, -0.01469165,  0.01417551],
       [-0.01469165,  0.08214145, -0.07925566],
       [ 0.01417551, -0.07925566,  0.07647125]])

In [41]:
w1 * A1 + w2 * A2 + w3 * A3

array([[60., 30., 20.],
       [30., 20., 15.],
       [20., 15., 12.]])

In [42]:
np.linalg.inv(A)

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

In [43]:
1 / w1 * A1

array([[0.0080948 , 0.00450097, 0.00316432],
       [0.00450097, 0.00250269, 0.00175947],
       [0.00316432, 0.00175947, 0.00123696]])

In [44]:
1 / w2 * A2

array([[ 0.04083313, -0.03940415, -0.04840816],
       [-0.03940415,  0.03802519,  0.04671409],
       [-0.04840816,  0.04671409,  0.05738845]])

In [45]:
1 / w3 * A3

array([[ 0.10107208, -0.56509682,  0.54524384],
       [-0.56509682,  3.15947213, -3.04847356],
       [ 0.54524384, -3.04847356,  2.94137459]])

In [46]:
1 / w1 * A1 + 1 / w2 * A2 + 1 / w3 * A3

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])